OpenILS::Utils::CStoreEditor
----------------------------

[source,perl]
.Standard Way
----
use OpenSRF::System;
use OpenILS::Utils::CStoreEditor;
OpenSRF::System->bootstrap_client(config_file => "/openils/conf/opensrf_core.xml");
OpenILS::Utils::CStoreEditor::init();
my $editor = OpenILS::Utils::CStoreEditor->new();
----

[source,perl]
.Function Interface
----
use OpenSRF::System;
use OpenILS::Utils::CStoreEditor qw/funcs/;
OpenSRF::System->bootstrap_client(config_file => "/openils/conf/opensrf_core.xml");
OpenILS::Utils::CStoreEditor::init();
my $editor = new_editor();
my $reports_editor = new_rstore_editor();
----

[source,perl]
.Or, with Cronscript.pm
----
use OpenILS::Utils::Cronscript;
my $script = OpenILS::Utils::Cronscript->new();
my $editor = $script->editor();
----

OpenILS::Utils::CStoreEditor
----------------------------

[source,perl]
.Authtoken
----
my $authtoken = $script->authenticate($credentials);
my $editor = $script->editor(authtoken=>$authtoken);
----

[source,perl]
.Always Transaction
----
my $editor = $script->editor(xact=>1);
----

[source,perl]
.Combination
----
my $editor = $script->editor(authtoken=>$authtoken,xact=>1);
----

Personalities
-------------

Correspond to controller in the IDL:

* open-ils.cstore
* open-ils.pcrud
* open-ils.reporter-store

[source,perl]
.Get Personality
----
my $app = $editor->personality;
----

[source,perl]
.Change Personality
----
$editor->personality('open-ils.pcrud');
----

[source,perl]
.Specify Personality
----
# PCRUD Personality
my $editor = $script->editor(personality=>'open-ils.pcrud');

# Reporter Store Personality
my $editor = $script->editor(personality=>'open-ils.reporter-store');

# Combination
my $editor = $script->editor(authtoken=>$authtoken,xact=>1,personality=>'open-ils.pcrud');
----


CStoreEditor Generated Methods
------------------------------

* create
* update
* delete
* retrieve
* batch_retrieve
* retrieve_all
* search

Remember me?
------------

....
<class id="ccs"
       controller="open-ils.cstore open-ils.pcrud"
       oils_obj:fieldmapper="config::copy_status"
       oils_persist:tablename="config.copy_status"
       oils_persist:restrict_primary="100"
       reporter:label="Copy Status"
       oils_persist:field_safe="true">
....

.Methods for Copy Status
* create_config_copy_status
* update_config_copy_status
* delete_config_copy_status
* retrieve_config_copy_status
* batch_retrieve_config_copy_status
* retrieve_all_config_copy_status
* search_config_copy_status


Create a config.copy_status
---------------------------

[source,perl]
----
my $ccs = Fieldmapper::config::copy_status->new();
$ccs->name('Red Alert');
$ccs->holdable('f');
$ccs->opac_visible('f');
$ccs->copy_active('t');
$ccs->restrict_copy_delete('t');
$ccs->is_available('t');

eval {
    $editor->xact_begin();
    $ccs = $editor->create_config_copy_status($ccs);
    $editor->commit();
};
if ($@) {
    die $@;
}
----

Update a config.copy_status
---------------------------

[source,perl]
----
$ccs->restrict_copy_delete('f');
eval {
    $editor->xact_begin();
    $ccs = $editor->update_config_copy_status($ccs);
    $editor->commit();
};
if ($@) {
    die $@;
}
----

Delete a config.copy_status
---------------------------

[source,perl]
----
eval {
    $editor->xact_begin();
    $ccs = $editor->delete_config_copy_status($ccs);
    $editor->commit();
};
if ($@) {
    die $@;
}
----

Something Missing?
------------------

[role="incremental"]
* isnew
* ischanged
* isdeleted

[role="incremental"]
CStoreEditor does not use them, BUT other backend calls do.
/BR/ Example: `open-ils.cat.asset.copy.fleshed.batch.update`

Getting Things
--------------

[source,perl]
.Retrieving a Copy Status
----
my $ccs = $editor->retrieve_config_copy_status(4);
----

[source,perl]
.Batch Retrieving a Copy Status
----
my $ccs_list = $editor->batch_retrieve_config_copy_status([4,5,6]);
----

[source,perl]
.Retrieve All Copy Statuses
----
my $ccs_list = $editor->retrieve_all_config_copy_status;
----

[source,perl]
.Searching Copy Statuses
----
my $ccs_list = $editor->search_config_copy_status({holdable => 'f'});
# Or, just the ids:
my $ccs_ids = $editor->search_config_copy_status({holdable => 'f'},{idlist=>1});
----

Getting More Things
-------------------

[source,perl]
.Getting Copies With Copy Status
----
my $acp_list = $editor->search_asset_copy(
    [{circ_lib => 6, deleted => 'f'},
     {flesh_depth => 1,
      flesh_fields => {acp => ['status']}}]);
----

[source,perl]
.Getting Copy Status from Call Numbers
----
my $acn_list = $editor->search_asset_call_number(
    [{owning_lib => 6, deleted => 'f'},
     {flesh_depth => 2,
      flesh_fields => {acn => ['copies'],
                       acp => ['status','location']}}]);
----

Limitations
-----------

* A way to do SQL without writing SQL.
* Doesn't always do the right thing.
/BR/Example: Deleting copies. Better to use `open-ils.cat.asset.copy.fleshed.batch.update`
* Can time out for large searches/tables.
/BR/Example: Retrieving all copies.

