OpenILS::Utils::Fieldmapper
---------------------------

[source,perl]
.Import
----
use OpenSRF::System;
use OpenSRF::Utils::SettingsClient;
use OpenILS::Utils::Fieldmapper;
OpenSRF::System->bootstrap_client(config_file => '/openils/conf/opensrf_core.xml');
Fieldmapper->import(IDL => OpenSRF::Utils::SettingsClient->new->config_value("IDL"));
----

*Bonus:* OpenILS::Utils::Cronscript does that for you when you bootstrap it.

Sidebar: Fieldmapper and the IDL
--------------------------------

....
<class id="ccs"
       controller="open-ils.cstore open-ils.pcrud"
       oils_obj:fieldmapper="config::copy_status"
       oils_persist:tablename="config.copy_status"
       oils_persist:restrict_primary="100"
       reporter:label="Copy Status"
       oils_persist:field_safe="true">
    <fields oils_persist:primary="id" oils_persist:sequence="config.copy_status_id_seq">
        <field name="holdable" reporter:datatype="bool"/>
        <field name="id" reporter:selector="name" reporter:datatype="id"/>
        <field name="name"  reporter:datatype="text" oils_persist:i18n="true"/>
        <field name="opac_visible" reporter:datatype="bool"/>
        <field name="copy_active" reporter:datatype="bool"/>
        <field name="restrict_copy_delete" reporter:datatype="bool"/>
        <field name="is_available" reporter:datatype="bool"/>
    </fields>
    <links/>
    <permacrud xmlns="http://open-ils.org/spec/opensrf/IDL/permacrud/v1">
        <actions>
            <create permission="CREATE_COPY_STATUS" global_required="true"/>
            <retrieve/>
            <update permission="UPDATE_COPY_STATUS" global_required="true"/>
            <delete permission="DELETE_COPY_STATUS" global_required="true"/>
        </actions>
    </permacrud>
</class>
....

Sidebar: Links
--------------

....
<links>
  <link field="billing_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="holds_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="ou_type" reltype="has_a" key="id" map="" class="aout"/>
  <link field="mailing_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="parent_ou" reltype="has_a" key="id" map="" class="aou"/>
  <link field="ill_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="fiscal_calendar" reltype="has_a" key="id" map="" class="acqfc"/>
  <link field="users" reltype="has_many" key="home_ou" map="" class="au"/>
  <link field="closed_dates" reltype="has_many" key="org_unit" map="" class="aoucd"/>
  <link field="children" reltype="has_many" key="parent_ou" map="" class="aou"/>
  <link field="circulations" reltype="has_many" key="circ_lib" map="" class="circ"/>
  <link field="settings" reltype="has_many" key="org_unit" map="" class="aous"/>
  <link field="addresses" reltype="has_many" key="org_unit" map="" class="aoa"/>
  <link field="checkins" reltype="has_many" key="checkin_lib" map="" class="circ"/>
  <link field="workstations" reltype="has_many" key="owning_lib" map="" class="aws"/>
  <link field="fund_alloc_pcts" reltype="has_many" key="org" map="" class="acqfap"/>
  <link field="copy_location_orders" reltype="has_many" key="org" map="" class="acplo"/>
  <link field="atc_prev_dests" reltype="has_many" key="prev_dest" map="" class="atc"/>
  <link field="resv_requests" reltype="has_many" key="request_lib" map="" class="bresv"/>
  <link field="resv_pickups" reltype="has_many" key="pickup_lib" map="" class="bresv"/>
  <link field="rsrc_types" reltype="has_many" key="owner" map="" class="brt"/>
  <link field="resources" reltype="has_many" key="owner" map="" class="brsrc"/>
  <link field="rsrc_attrs" reltype="has_many" key="owner" map="" class="bra"/>
  <link field="attr_vals" reltype="has_many" key="owner" map="" class="brav"/>
  <link field="hours_of_operation" reltype="might_have" key="id" map="" class="aouhoo"/>
</links>
....

Fieldmapper Functions
---------------------

[source,perl]
----
# Get List of Class Names:
my @classes = Fieldmapper::classes();

# Get class for a hint (class ID from IDL):
my $aou_class = Fieldmapper::class_for_hint('aou');
----

Fieldmapper Object/Class Methods
--------------------------------

[source,perl]
----
# Get the class name:
my $var = $obj_or_class->class_name;

# Get the primary ID field:
my $id_field = $obj_or_class->Identity;

# Get the database table:
my $table_name = $obj_or_class->Table;

# Get the list of controllers (arrayref):
my $controllers = $obj_or_class->Controller;

# Get the json_hint (IDL class id):
my $hint = $obj_or_class->json_hint;
----

Object/Class Methods For Fields
-------------------------------

[source,perl]
----
# Get a list of the fields:
my @fields = $obj_or_class->properties;

# Get a list of the real fields:
my @real_fields = $obj_or_class->real_fields;

# Check if class/object has a field with a certain name:
my $result = $obj_or_class->has_field($field_name);

# Get a hashref of a field's info:
my $field_info = $obj_or_class->FieldInfo($field_name);

# Get the field data type:
my $data_type = $obj_or_class->FieldDataType($field_name);

# Check if field is required:
my $required = $obj_or_class->RequiredField($field_name);
----

Object/Class Methods for Either Fields or Classes
-------------------------------------------------

[source,perl]
----
# Check if a class is a virtual class:
my $is_virtual = $obj_or_class->is_virtual;

# Check if a field is virtual:
my $is_virtual = $obj_or_class->is_virtual($field_name);

# Check if a class is readonly:
my $is_readonly = $obj_or_class->is_readonly;

# Check if a field is readonly:
my $is_readonly = $obj_or_class->is_readonly($field_name);
----

Fieldmapper Object Methods
--------------------------

[source,perl]
----
# Make a copy of the object:
my $copy = $obj->clone;

# Export the object to a hashref:
my $hash = $obj->to_bare_hash;

# Export the object to a XML string:
my $xml = $obj->toXML;

# Validate the content of a field:
my $is_valid = $obj->ValidateField($field_name);
----

Constructors
------------

[source,perl]
----
# Usual way to create an object:
my $acp = Fieldmapper::asset::copy->new();

# Create instance from a class:
my $obj = $class->new();

# Create instance from a class name:
my $obj = $class_name->new();

# Create instance from a hashref:
my $obj = $class_or_obj->from_bare_hash($hashref);
----

[source,perl]
----
# New takes an arrayref of field values:
my $obj = $class->new($arrayref);
----

Special Object Methods
----------------------

[source,perl]
----
# Newly created object:
$obj->isnew(1);

# Modified object:
$obj->ischanged(1);

# Deleted object:
$obj->isdeleted(1);
----
