OpenILS::Utils::Fieldmapper
---------------------------

[source,perl]
.Import
----
use OpenSRF::System;
use OpenSRF::Utils::SettingsClient;
use OpenILS::Utils::Fieldmapper;
OpenSRF::System->bootstrap_client(config_file => '/openils/conf/opensrf_core.xml');
Fieldmapper->import(IDL => OpenSRF::Utils::SettingsClient->new->config_value("IDL"));
----

*Bonus:* Cronscript does that for you when you bootstrap it.

[source,perl]
.Get List of Class Names
----
my @classes = Fieldmapper::classes();
----

[source,perl]
.Get class for a hint
----
my $aou_class = Fieldmapper::class_for_hint('aou');
----

[source,perl]
.Create Instance From a Class
----
my $aou_obj = $aou_class->new();
----

Usual Way To Instantiate an Object
----------------------------------

[source,perl]
----
my $item = Fieldmapper::asset::copy->new();
$item->barcode('31234005678911');
$item->call_number(OILS_PRECAT_CALL_NUMBER);
$item->dummy_title('Red Alert');
$item->dummy_author('Peter George');
$item->circ_lib($user->home_ou());
$item->circulate('t');
$item->holdable('t');
$item->opac_visible('f');
$item->deleted('f');
$item->fine_level(OILS_PRECAT_COPY_FINE_LEVEL);
$item->loan_duration(OILS_PRECAT_COPY_LOAN_DURATION);
$item->location(1);
$item->status(0);
$item->editor($user->id());
$item->creator($user->id());
$item->isnew(1);
----

Sidebar: Fieldmapper and the IDL
--------------------------------

....
<class id="ccs"
       controller="open-ils.cstore open-ils.pcrud"
       oils_obj:fieldmapper="config::copy_status"
       oils_persist:tablename="config.copy_status"
       oils_persist:restrict_primary="100"
       reporter:label="Copy Status"
       oils_persist:field_safe="true">
    <fields oils_persist:primary="id" oils_persist:sequence="config.copy_status_id_seq">
        <field name="holdable" reporter:datatype="bool"/>
        <field name="id" reporter:selector="name" reporter:datatype="id"/>
        <field name="name"  reporter:datatype="text" oils_persist:i18n="true"/>
        <field name="opac_visible" reporter:datatype="bool"/>
        <field name="copy_active" reporter:datatype="bool"/>
        <field name="restrict_copy_delete" reporter:datatype="bool"/>
        <field name="is_available" reporter:datatype="bool"/>
    </fields>
    <links/>
    <permacrud xmlns="http://open-ils.org/spec/opensrf/IDL/permacrud/v1">
        <actions>
            <create permission="CREATE_COPY_STATUS" global_required="true"/>
            <retrieve/>
            <update permission="UPDATE_COPY_STATUS" global_required="true"/>
            <delete permission="DELETE_COPY_STATUS" global_required="true"/>
        </actions>
    </permacrud>
</class>
....

Sidebar: Links
--------------

....
<links>
  <link field="billing_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="holds_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="ou_type" reltype="has_a" key="id" map="" class="aout"/>
  <link field="mailing_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="parent_ou" reltype="has_a" key="id" map="" class="aou"/>
  <link field="ill_address" reltype="has_a" key="id" map="" class="aoa"/>
  <link field="fiscal_calendar" reltype="has_a" key="id" map="" class="acqfc"/>
  <link field="users" reltype="has_many" key="home_ou" map="" class="au"/>
  <link field="closed_dates" reltype="has_many" key="org_unit" map="" class="aoucd"/>
  <link field="children" reltype="has_many" key="parent_ou" map="" class="aou"/>
  <link field="circulations" reltype="has_many" key="circ_lib" map="" class="circ"/>
  <link field="settings" reltype="has_many" key="org_unit" map="" class="aous"/>
  <link field="addresses" reltype="has_many" key="org_unit" map="" class="aoa"/>
  <link field="checkins" reltype="has_many" key="checkin_lib" map="" class="circ"/>
  <link field="workstations" reltype="has_many" key="owning_lib" map="" class="aws"/>
  <link field="fund_alloc_pcts" reltype="has_many" key="org" map="" class="acqfap"/>
  <link field="copy_location_orders" reltype="has_many" key="org" map="" class="acplo"/>
  <link field="atc_prev_dests" reltype="has_many" key="prev_dest" map="" class="atc"/>
  <link field="resv_requests" reltype="has_many" key="request_lib" map="" class="bresv"/>
  <link field="resv_pickups" reltype="has_many" key="pickup_lib" map="" class="bresv"/>
  <link field="rsrc_types" reltype="has_many" key="owner" map="" class="brt"/>
  <link field="resources" reltype="has_many" key="owner" map="" class="brsrc"/>
  <link field="rsrc_attrs" reltype="has_many" key="owner" map="" class="bra"/>
  <link field="attr_vals" reltype="has_many" key="owner" map="" class="brav"/>
  <link field="hours_of_operation" reltype="might_have" key="id" map="" class="aouhoo"/>
</links>
....

Fielmapper Object Methods
-------------------------

[source,perl]
----
# Get the class name:
my $var = $obj->class_name;

# Get the primary ID field:
my $id_field = $obj->Identity;

# Get the database table:
my $table_name = $obj->Table;

# Get the list of controllers (arrayref):
my $controllers = $obj->Controller;

# Get the json_hint (IDL class id):
my $hint = $obj->json_hint;

# Make a copy of the object:
my $copy = $obj->clone;

# Export the fields to a hashref:
my $hash = $obj->to_bare_hash;

# Export the fields to a XML string:
my $xml = $obj->toXML;
----
